services:
  - type: web
    name: vineetrawat-associates
    runtime: node
    plan: free
    branch: main
    autoDeployTrigger: commit
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
