backend:
  name: turbo-github
  turbo_site_id: YOUR_SITE_ID
  branch: main

media_folder: public/uploads
public_folder: /uploads

collections:
  - name: blog
    label: Articles
    label_singular: Article
    folder: src/content/blog
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text", required: false }
      - { label: "Category", name: "category", widget: "string", required: false }
      - { label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD", date_format: "YYYY-MM-DD", time_format: false }
      - { label: "Draft", name: "draft", widget: "boolean", default: false, required: false }
      - { label: "Body", name: "body", widget: "markdown" }
